name: Analysis
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: oven-sh/setup-bun@v1
        with:
          bun-version: latest
      # Cacheした方が遅くなる
      # - name: Setup Cache
      #   uses: actions/cache@v2
      #   with:
      #     path: ~/.bun/install/cache
      #     key: ${{ hashFiles('**/bun.lockb') }}
      - run: bun install --no-save
      - name: Test
        run: bun test
